GET http://localhost:3000/graphql?query={books{id title author publicationYear genre isbn}}
###
GET http://localhost:3000/graphql?query=query($id: ID!){book(id: $id){id title author}}&variables={"id": "6468b40c269f04c2ffaea739"}
###
POST http://localhost:3000/graphql
Content-Type: application/json

{
  "query": "mutation { createBook(title: \"New Book\", author: \"John Doe\", publicationYear: 2022, genre: \"Fiction\", isbn: \"123456789\") { id title author publicationYear genre isbn } }"
}
###
POST http://localhost:3000/graphql
Content-Type: application/json

{
  "query": "mutation { updateBook(id: \"6468b40c269f04c2ffaea739\", title: \"Updated Book\", author: \"Jane Doe\") { id title author publicationYear genre isbn } }"
}


### Render
POST http://localhost:3000/graphql
Content-Type: application/json

{
  "query": "mutation { deleteBook(id: \"647233a1de4979058d035fb7\") { id title author publicationYear genre isbn } }"
}
